/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoWc {
        /**
          * The first name
         */
        "first": string;
        "timeout": number;
    }
    interface DxPlotRaw {
        /**
          * The first name
         */
        "first": string;
        "timeout": number;
    }
}
declare global {
    interface HTMLDemoWcElement extends Components.DemoWc, HTMLStencilElement {
    }
    var HTMLDemoWcElement: {
        prototype: HTMLDemoWcElement;
        new (): HTMLDemoWcElement;
    };
    interface HTMLDxPlotRawElement extends Components.DxPlotRaw, HTMLStencilElement {
    }
    var HTMLDxPlotRawElement: {
        prototype: HTMLDxPlotRawElement;
        new (): HTMLDxPlotRawElement;
    };
    interface HTMLElementTagNameMap {
        "demo-wc": HTMLDemoWcElement;
        "dx-plot-raw": HTMLDxPlotRawElement;
    }
}
declare namespace LocalJSX {
    interface DemoWc {
        /**
          * The first name
         */
        "first"?: string;
        "timeout"?: number;
    }
    interface DxPlotRaw {
        /**
          * The first name
         */
        "first"?: string;
        "timeout"?: number;
    }
    interface IntrinsicElements {
        "demo-wc": DemoWc;
        "dx-plot-raw": DxPlotRaw;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-wc": LocalJSX.DemoWc & JSXBase.HTMLAttributes<HTMLDemoWcElement>;
            "dx-plot-raw": LocalJSX.DxPlotRaw & JSXBase.HTMLAttributes<HTMLDxPlotRawElement>;
        }
    }
}
