/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Column, Row } from "./components/data-table/data-table";
import { TType } from "./components/input-field/input-field";
export namespace Components {
    interface ColorPicker {
        "defaultValue": string;
        "resettable": boolean;
    }
    interface DemoWc {
        /**
          * The name
         */
        "name": string;
        "timeout": number;
    }
    interface DxDataTable {
        "columns": Column[] | string;
        "name": string;
        "rows": Row[] | string;
    }
    interface DxHeaderBar {
        "menuUrl": string;
    }
    interface DxHeaderBarControl {
    }
    interface DxInputField {
        "disabled": boolean;
        "expected": string;
        "expectedError": string;
        "isAlphanumeric": boolean;
        "isWord": boolean;
        "label": string;
        "max"?: number;
        "min"?: number;
        "placeholder": string;
        "readonly": boolean;
        "regex": string;
        "required": boolean;
        "trim": boolean;
        "type": TType;
        "value": string;
    }
    interface DxPageLoader {
        "defaultTemplateUrl": string;
        "templateUrl": string;
        "useHash": boolean;
    }
    interface DxPlotRaw {
    }
    interface DxRtLabel {
        "topicName": string;
    }
    interface DxRtMeter {
        "animateColor": string;
        "animateDuration": string;
        "bgColor": string;
        "color": string;
        "name": string;
        "size": "xx-small" | "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
        "topicName": string;
        "unit": string;
    }
    interface DxRtPlot {
        "baseUrl": string;
        "begin": string;
        "end": string;
        "interval": number;
        "legendFloated": boolean;
        "legendSize": number;
        "name": string;
        "period": number;
        "realtime": boolean;
        "slice": boolean;
        "spark": boolean;
        "tags": string;
    }
    interface DxRtValue {
        "animateColor": string;
        "animateDuration": string;
        "bgColor": string;
        "color": string;
        "inline": boolean;
        "topicName": string;
    }
    interface InputWrapper {
        "label": string;
        "type": string;
        "value": string;
    }
}
declare global {
    interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {
    }
    var HTMLColorPickerElement: {
        prototype: HTMLColorPickerElement;
        new (): HTMLColorPickerElement;
    };
    interface HTMLDemoWcElement extends Components.DemoWc, HTMLStencilElement {
    }
    var HTMLDemoWcElement: {
        prototype: HTMLDemoWcElement;
        new (): HTMLDemoWcElement;
    };
    interface HTMLDxDataTableElement extends Components.DxDataTable, HTMLStencilElement {
    }
    var HTMLDxDataTableElement: {
        prototype: HTMLDxDataTableElement;
        new (): HTMLDxDataTableElement;
    };
    interface HTMLDxHeaderBarElement extends Components.DxHeaderBar, HTMLStencilElement {
    }
    var HTMLDxHeaderBarElement: {
        prototype: HTMLDxHeaderBarElement;
        new (): HTMLDxHeaderBarElement;
    };
    interface HTMLDxHeaderBarControlElement extends Components.DxHeaderBarControl, HTMLStencilElement {
    }
    var HTMLDxHeaderBarControlElement: {
        prototype: HTMLDxHeaderBarControlElement;
        new (): HTMLDxHeaderBarControlElement;
    };
    interface HTMLDxInputFieldElement extends Components.DxInputField, HTMLStencilElement {
    }
    var HTMLDxInputFieldElement: {
        prototype: HTMLDxInputFieldElement;
        new (): HTMLDxInputFieldElement;
    };
    interface HTMLDxPageLoaderElement extends Components.DxPageLoader, HTMLStencilElement {
    }
    var HTMLDxPageLoaderElement: {
        prototype: HTMLDxPageLoaderElement;
        new (): HTMLDxPageLoaderElement;
    };
    interface HTMLDxPlotRawElement extends Components.DxPlotRaw, HTMLStencilElement {
    }
    var HTMLDxPlotRawElement: {
        prototype: HTMLDxPlotRawElement;
        new (): HTMLDxPlotRawElement;
    };
    interface HTMLDxRtLabelElement extends Components.DxRtLabel, HTMLStencilElement {
    }
    var HTMLDxRtLabelElement: {
        prototype: HTMLDxRtLabelElement;
        new (): HTMLDxRtLabelElement;
    };
    interface HTMLDxRtMeterElement extends Components.DxRtMeter, HTMLStencilElement {
    }
    var HTMLDxRtMeterElement: {
        prototype: HTMLDxRtMeterElement;
        new (): HTMLDxRtMeterElement;
    };
    interface HTMLDxRtPlotElement extends Components.DxRtPlot, HTMLStencilElement {
    }
    var HTMLDxRtPlotElement: {
        prototype: HTMLDxRtPlotElement;
        new (): HTMLDxRtPlotElement;
    };
    interface HTMLDxRtValueElement extends Components.DxRtValue, HTMLStencilElement {
    }
    var HTMLDxRtValueElement: {
        prototype: HTMLDxRtValueElement;
        new (): HTMLDxRtValueElement;
    };
    interface HTMLInputWrapperElement extends Components.InputWrapper, HTMLStencilElement {
    }
    var HTMLInputWrapperElement: {
        prototype: HTMLInputWrapperElement;
        new (): HTMLInputWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "color-picker": HTMLColorPickerElement;
        "demo-wc": HTMLDemoWcElement;
        "dx-data-table": HTMLDxDataTableElement;
        "dx-header-bar": HTMLDxHeaderBarElement;
        "dx-header-bar-control": HTMLDxHeaderBarControlElement;
        "dx-input-field": HTMLDxInputFieldElement;
        "dx-page-loader": HTMLDxPageLoaderElement;
        "dx-plot-raw": HTMLDxPlotRawElement;
        "dx-rt-label": HTMLDxRtLabelElement;
        "dx-rt-meter": HTMLDxRtMeterElement;
        "dx-rt-plot": HTMLDxRtPlotElement;
        "dx-rt-value": HTMLDxRtValueElement;
        "input-wrapper": HTMLInputWrapperElement;
    }
}
declare namespace LocalJSX {
    interface ColorPicker {
        "defaultValue"?: string;
        "onColor-changed"?: (event: CustomEvent<any>) => void;
        "resettable"?: boolean;
    }
    interface DemoWc {
        /**
          * The name
         */
        "name"?: string;
        "onInput-change"?: (event: CustomEvent<any>) => void;
        "timeout"?: number;
    }
    interface DxDataTable {
        "columns"?: Column[] | string;
        "name"?: string;
        "rows"?: Row[] | string;
    }
    interface DxHeaderBar {
        "menuUrl"?: string;
    }
    interface DxHeaderBarControl {
    }
    interface DxInputField {
        "disabled"?: boolean;
        "expected"?: string;
        "expectedError"?: string;
        "isAlphanumeric"?: boolean;
        "isWord"?: boolean;
        "label"?: string;
        "max"?: number;
        "min"?: number;
        "onColor-changed"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "regex"?: string;
        "required"?: boolean;
        "trim"?: boolean;
        "type"?: TType;
        "value"?: string;
    }
    interface DxPageLoader {
        "defaultTemplateUrl"?: string;
        "templateUrl"?: string;
        "useHash"?: boolean;
    }
    interface DxPlotRaw {
    }
    interface DxRtLabel {
        "topicName"?: string;
    }
    interface DxRtMeter {
        "animateColor"?: string;
        "animateDuration"?: string;
        "bgColor"?: string;
        "color"?: string;
        "name"?: string;
        "size"?: "xx-small" | "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
        "topicName"?: string;
        "unit"?: string;
    }
    interface DxRtPlot {
        "baseUrl"?: string;
        "begin"?: string;
        "end"?: string;
        "interval"?: number;
        "legendFloated"?: boolean;
        "legendSize"?: number;
        "name"?: string;
        "period"?: number;
        "realtime"?: boolean;
        "slice"?: boolean;
        "spark"?: boolean;
        "tags"?: string;
    }
    interface DxRtValue {
        "animateColor"?: string;
        "animateDuration"?: string;
        "bgColor"?: string;
        "color"?: string;
        "inline"?: boolean;
        "topicName"?: string;
    }
    interface InputWrapper {
        "label"?: string;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        "type"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "color-picker": ColorPicker;
        "demo-wc": DemoWc;
        "dx-data-table": DxDataTable;
        "dx-header-bar": DxHeaderBar;
        "dx-header-bar-control": DxHeaderBarControl;
        "dx-input-field": DxInputField;
        "dx-page-loader": DxPageLoader;
        "dx-plot-raw": DxPlotRaw;
        "dx-rt-label": DxRtLabel;
        "dx-rt-meter": DxRtMeter;
        "dx-rt-plot": DxRtPlot;
        "dx-rt-value": DxRtValue;
        "input-wrapper": InputWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-picker": LocalJSX.ColorPicker & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
            "demo-wc": LocalJSX.DemoWc & JSXBase.HTMLAttributes<HTMLDemoWcElement>;
            "dx-data-table": LocalJSX.DxDataTable & JSXBase.HTMLAttributes<HTMLDxDataTableElement>;
            "dx-header-bar": LocalJSX.DxHeaderBar & JSXBase.HTMLAttributes<HTMLDxHeaderBarElement>;
            "dx-header-bar-control": LocalJSX.DxHeaderBarControl & JSXBase.HTMLAttributes<HTMLDxHeaderBarControlElement>;
            "dx-input-field": LocalJSX.DxInputField & JSXBase.HTMLAttributes<HTMLDxInputFieldElement>;
            "dx-page-loader": LocalJSX.DxPageLoader & JSXBase.HTMLAttributes<HTMLDxPageLoaderElement>;
            "dx-plot-raw": LocalJSX.DxPlotRaw & JSXBase.HTMLAttributes<HTMLDxPlotRawElement>;
            "dx-rt-label": LocalJSX.DxRtLabel & JSXBase.HTMLAttributes<HTMLDxRtLabelElement>;
            "dx-rt-meter": LocalJSX.DxRtMeter & JSXBase.HTMLAttributes<HTMLDxRtMeterElement>;
            "dx-rt-plot": LocalJSX.DxRtPlot & JSXBase.HTMLAttributes<HTMLDxRtPlotElement>;
            "dx-rt-value": LocalJSX.DxRtValue & JSXBase.HTMLAttributes<HTMLDxRtValueElement>;
            "input-wrapper": LocalJSX.InputWrapper & JSXBase.HTMLAttributes<HTMLInputWrapperElement>;
        }
    }
}
