/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoWc {
        /**
          * The name
         */
        "name": string;
        "timeout": number;
    }
    interface DxPageLoader {
        "defaultTemplateUrl": string;
        "templateUrl": string;
        "useHash": boolean;
    }
    interface DxPlotRaw {
    }
    interface DxRtMeter {
        "animateColor": string;
        "animateDuration": string;
        "bgColor": string;
        "color": string;
        "name": string;
        "size": "xx-small" | "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
        "topicName": string;
        "unit": string;
    }
    interface DxRtPlot {
    }
    interface DxRtValue {
        "animateColor": string;
        "animateDuration": string;
        "bgColor": string;
        "color": string;
        "inline": boolean;
        "topicName": string;
    }
}
declare global {
    interface HTMLDemoWcElement extends Components.DemoWc, HTMLStencilElement {
    }
    var HTMLDemoWcElement: {
        prototype: HTMLDemoWcElement;
        new (): HTMLDemoWcElement;
    };
    interface HTMLDxPageLoaderElement extends Components.DxPageLoader, HTMLStencilElement {
    }
    var HTMLDxPageLoaderElement: {
        prototype: HTMLDxPageLoaderElement;
        new (): HTMLDxPageLoaderElement;
    };
    interface HTMLDxPlotRawElement extends Components.DxPlotRaw, HTMLStencilElement {
    }
    var HTMLDxPlotRawElement: {
        prototype: HTMLDxPlotRawElement;
        new (): HTMLDxPlotRawElement;
    };
    interface HTMLDxRtMeterElement extends Components.DxRtMeter, HTMLStencilElement {
    }
    var HTMLDxRtMeterElement: {
        prototype: HTMLDxRtMeterElement;
        new (): HTMLDxRtMeterElement;
    };
    interface HTMLDxRtPlotElement extends Components.DxRtPlot, HTMLStencilElement {
    }
    var HTMLDxRtPlotElement: {
        prototype: HTMLDxRtPlotElement;
        new (): HTMLDxRtPlotElement;
    };
    interface HTMLDxRtValueElement extends Components.DxRtValue, HTMLStencilElement {
    }
    var HTMLDxRtValueElement: {
        prototype: HTMLDxRtValueElement;
        new (): HTMLDxRtValueElement;
    };
    interface HTMLElementTagNameMap {
        "demo-wc": HTMLDemoWcElement;
        "dx-page-loader": HTMLDxPageLoaderElement;
        "dx-plot-raw": HTMLDxPlotRawElement;
        "dx-rt-meter": HTMLDxRtMeterElement;
        "dx-rt-plot": HTMLDxRtPlotElement;
        "dx-rt-value": HTMLDxRtValueElement;
    }
}
declare namespace LocalJSX {
    interface DemoWc {
        /**
          * The name
         */
        "name"?: string;
        "timeout"?: number;
    }
    interface DxPageLoader {
        "defaultTemplateUrl"?: string;
        "templateUrl"?: string;
        "useHash"?: boolean;
    }
    interface DxPlotRaw {
    }
    interface DxRtMeter {
        "animateColor"?: string;
        "animateDuration"?: string;
        "bgColor"?: string;
        "color"?: string;
        "name"?: string;
        "size"?: "xx-small" | "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
        "topicName"?: string;
        "unit"?: string;
    }
    interface DxRtPlot {
    }
    interface DxRtValue {
        "animateColor"?: string;
        "animateDuration"?: string;
        "bgColor"?: string;
        "color"?: string;
        "inline"?: boolean;
        "topicName"?: string;
    }
    interface IntrinsicElements {
        "demo-wc": DemoWc;
        "dx-page-loader": DxPageLoader;
        "dx-plot-raw": DxPlotRaw;
        "dx-rt-meter": DxRtMeter;
        "dx-rt-plot": DxRtPlot;
        "dx-rt-value": DxRtValue;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-wc": LocalJSX.DemoWc & JSXBase.HTMLAttributes<HTMLDemoWcElement>;
            "dx-page-loader": LocalJSX.DxPageLoader & JSXBase.HTMLAttributes<HTMLDxPageLoaderElement>;
            "dx-plot-raw": LocalJSX.DxPlotRaw & JSXBase.HTMLAttributes<HTMLDxPlotRawElement>;
            "dx-rt-meter": LocalJSX.DxRtMeter & JSXBase.HTMLAttributes<HTMLDxRtMeterElement>;
            "dx-rt-plot": LocalJSX.DxRtPlot & JSXBase.HTMLAttributes<HTMLDxRtPlotElement>;
            "dx-rt-value": LocalJSX.DxRtValue & JSXBase.HTMLAttributes<HTMLDxRtValueElement>;
        }
    }
}
